alias cchown="sudo chown -R ucul:ucul"
alias cde="docker exec -ti"
alias cgbn="git branch --show-current"
alias cgca="git commit --amend"
alias cgd="git branch -d"
alias cgD="git branch -D"
alias cgg="git log --oneline --pretty=oneline --graph"
alias cggv="git log --pretty=full --graph"
alias cggvv="git log --pretty=fuller --graph"
alias cgpru="cgprune"
alias cgprune="git remote prune origin"
alias cgri="git rebase --rebase-merges -i"
alias cgrm="git rebase --rebase-merges"
alias cl="clear"
