alias -g cchown="sudo chown -R ucul:ucul"
alias -g cde="docker exec -ti"
alias -g cgbn="git branch --show-current"
alias -g cgca="git commit --amend"
alias -g cgd="git branch -d"
alias -g cgD="git branch -D"
alias -g cgg="git log --oneline --pretty=oneline --graph"
alias -g cggv="git log --pretty=full --graph"
alias -g cggvv="git log --pretty=fuller --graph"
alias -g cgpru="cgprune"
alias -g cgprune="git remote prune origin"
alias -g cgri="git rebase --rebase-merges -i"
alias -g cgrm="git rebase --rebase-merges"
alias -g cl="clear"
