FROM debian:latest AS base
# RUN apt-get update
# RUN apt-get install -y vim
# RUN apt-get install -y curl
# RUN apt-get install -y git
# RUN apt-get install -y zsh
# RUN yes Y | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# RUN git clone https://github.com/spaceship-prompt/spaceship-prompt.git "/root/.oh-my-zsh/custom/themes/spaceship-prompt" --depth=1 \
#     && ln -s "/root/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme" "/root/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
CMD [ "tail", "-f", "/dev/null" ]

FROM base AS final-volume

FROM base AS final-copy
RUN cd /root && mkdir zshconfig
COPY ./ /root/zshconfig
